# Use with https://hub.docker.com/r/jwilder/nginx-proxy/
# Make sure to $>docker network create webproxy
version: "3.2"
services:
    db:
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
    api:
        container_name: 'django-redux-api'
        build: 
            context: ./api/
            dockerfile: ./Dockerfile
        volumes:
            - ./api:/code
        command: ./manage.py runserver 0.0.0.0:80
        expose:
            - "80"
        env_file: .env-api 
        stdin_open: true
        tty: true

        depends_on:
            - db

    ui:
        build:
            context: ./ui/
            dockerfile: ./Dockerfile
        env_file: .env-ui
        volumes:
            - "./ui/src/:/usr/src/app/src"
        expose: 
            - "80"

networks:
    default:
        external:
            name: webproxy
