"""
Django Test Settings

Generated by 'django-admin startproject' using Django 2.0.8.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

os.environ["STAGE"] = "test"
from config.settings import *
BASE_DIR = os.path.normpath(os.path.dirname(os.path.abspath(__file__)))


ALLOWED_HOSTS = ['*',]

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'test-db.sqlite'),
    }
}

STATIC_URL = os.getenv('STATIC_URL')
MEDIA_URL = '/media/'

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
MEDIA_ROOT = os.path.join(BASE_DIR, 'fixtures')
