# base image
FROM jekyll/builder:4.0 as build

# set working directory
WORKDIR /usr/src/app

COPY ./src /usr/src/app

RUN bundle install && bundle exec jekyll build

FROM nginx
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /usr/src/app/build /usr/share/nginx/html
